Tour creation - Stop Creation - Tour Update
Eva-Gaivoronski/altas pull request #17
Opened 2024-01-16 06:59 UTC by lhedrick05

I realize now that I should have broken these up into different branches but I was in too deep already by the time I realized.

2024-01-16 19:55 UTC, Cresence requested changes
Insight on User.java needed before merge approval

2024-01-16 19:55 UTC, Cresence commented on src/main/java/liftoff/atlas/getcultured/models/User.java
This class has some significant implications of contrasting functionality. 

Everything else seems harmless (I've marked others resolved), this file I'd like to hear the compare/contrast between what was left as template in main vs. what is being used in the Tour creation - branch.

2024-01-17 00:29 UTC, AlexMerchant commented on src/main/java/liftoff/atlas/getcultured/models/User.java
Noting this for our call:

Major differences in how the User is implemented in this 'tour-creation' branch against my most recent implementation in my 'user-authentication' branch are:

- I do not extend my class from AbstractEntity
- I have the ID of the user's id as 'userID' and it is defined directly in User.java
- I have the username of the user's defined as 'username' and directly in User.java
- tour-creation: userEmail member; user-auth: emailAddress
- passwordHash defined on User and acocmpanying methods
- I handle parameterized @Validations in the user sign-up DTO
- UserGroup associations are defined in a Set<UserGroup> attribute; with a @ManyToMany relationship
- Methods to add and remove UserGroup to the 'userGroups' Set; as well as getter and setters
- Set up a @OneToOne relationship between User and UserProfileDetails
- Moved firstName, lastName, location (and added aboutMe) to UserProfileDetails class
- Moved List<Tour> and List<UserReview> properties to UserProfileDetails class
- Slightly varied constructors
- Other getters and setters

2024-01-17 02:49 UTC, Cresence approved these changes
Merge conflicts resolved in group meeting. Looks good to me.

2024-01-17 02:49 UTC, merged